
server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
#          uri: file://D:/private/study/gitRepository/study/ecomerce.yml
          uri: https://github.com/suersehii1/study.git

