server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: lb://FIRSTSERVICE
          predicates:
            - Path=/first-service/**
        - id: second-service
          uri: lb://SECONDSERVICE
          predicates:
            - Path=/second-service/**
